AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy SOLO la tua immagine Docker Hub su ECS Fargate

Parameters:
  DockerHubImage:
    Type: String
    Default: "meneghin/cdc-pipeline:latest"  # <-- LA TUA IMMAGINE SU DOCKER HUB
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Seleziona 2 subnet pubbliche della tua VPC
  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security Group con outbound internet (per Kafka e HTTP)

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: cdc-pipeline-cluster

  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/cdc-pipeline
      RetentionInDays: 30

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: cdc-pipeline
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: "2048"
      Memory: "4096"
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: cdc-pipeline
          Image: !Ref DockerHubImage
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: pipeline

  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref TaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets: !Ref SubnetIds
          SecurityGroups:
            - !Ref SecurityGroupId
          AssignPublicIp: true  # Per accesso Kafka esterno e chiamate HTTP

Outputs:
  ClusterName:
    Value: !Ref ECSCluster
  ServiceName:
    Value: !Ref ECSService
  LogGroup:
    Value: !Ref LogGroup
    Description: Guarda qui i log del tuo container